config/routes.rb
Rails.application.routes.draw do
  resources :counters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/counter.rb
class Counter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # for POSTman requests, comment out later
  skip_before_action :verify_authenticity_token
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: %i[ show edit update destroy ]

  # GET /counters or /counters.json
  def index
    render json: Counter.all, status: :ok
  end

  # GET /counters/1 or /counters/1.json
  def show
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
  end

  # POST /counters or /counters.json
  def create
    counter = Counter.create!(counter_params)
    render json: counter, status: :created
  end

  # PATCH/PUT /counters/1 or /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to counter_url(@counter), notice: "Counter was successfully updated." }
        format.json { render :show, status: :ok, location: @counter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1 or /counters/1.json
  def destroy
    @counter.destroy

    respond_to do |format|
      format.html { redirect_to counters_url, notice: "Counter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def counter_params
      params.permit(:name, :style, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/views/counters/_counter.html.erb
<div id="<%= dom_id counter %>">
  <p>
    <strong>Name:</strong>
    <%= counter.name %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= counter.style %>
  </p>

  <p>
    <strong>Count:</strong>
    <%= counter.count %>
  </p>

</div>

app/views/counters/_form.html.erb
<%= form_with(model: counter) do |form| %>
  <% if counter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
        <% counter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :count, style: "display: block" %>
    <%= form.number_field :count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing counter</h1>

<%= render "form", counter: @counter %>

<br>

<div>
  <%= link_to "Show this counter", @counter %> |
  <%= link_to "Back to counters", counters_path %>
</div>

app/views/counters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Counters</h1>

<div id="counters">
  <% @counters.each do |counter| %>
    <%= render counter %>
    <p>
      <%= link_to "Show this counter", counter %>
    </p>
  <% end %>
</div>

<%= link_to "New counter", new_counter_path %>

app/views/counters/new.html.erb
<h1>New counter</h1>

<%= render "form", counter: @counter %>

<br>

<div>
  <%= link_to "Back to counters", counters_path %>
</div>

app/views/counters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @counter %>

<div>
  <%= link_to "Edit this counter", edit_counter_path(@counter) %> |
  <%= link_to "Back to counters", counters_path %>

  <%= button_to "Destroy this counter", @counter, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>